{"name": "test_fail2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail2():\n>       assert False\nE       assert False\n\ntest_fail.py:9: AssertionError"}, "start": 1744878772626, "stop": 1744878772626, "uuid": "1f188f34-1cb7-4581-b32e-7b77bb0323bf", "historyId": "4f39991870c75bdeb73cdb83d5f0a386", "testCaseId": "4f39991870c75bdeb73cdb83d5f0a386", "fullName": "test_fail#test_fail2", "labels": [{"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Air-Donchulesko.local"}, {"name": "thread", "value": "56996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fail"}]}