{"name": "test_fail2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail2():\n>       assert False\nE       assert False\n\ntests/simple/test_fail.py:9: AssertionError"}, "start": 1744885261397, "stop": 1744885261398, "uuid": "7627ac9d-119d-45ff-8bed-d892107ff94f", "historyId": "c34ce9c1ddd89c5349df16e9084d0f7d", "testCaseId": "c34ce9c1ddd89c5349df16e9084d0f7d", "fullName": "tests.simple.test_fail#test_fail2", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Air-Donchulesko.local"}, {"name": "thread", "value": "58391-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}