{"name": "test_fail2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail2():\n>       assert False\nE       assert False\n\ntest_fail.py:9: AssertionError"}, "start": 1744878873645, "stop": 1744878873645, "uuid": "42b0be31-c3ac-4518-8052-da9fb1bf26f1", "historyId": "4f39991870c75bdeb73cdb83d5f0a386", "testCaseId": "4f39991870c75bdeb73cdb83d5f0a386", "fullName": "test_fail#test_fail2", "labels": [{"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Air-Donchulesko.local"}, {"name": "thread", "value": "57039-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fail"}]}